// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category_groups.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const categoryTextExistsForUser = `-- name: CategoryTextExistsForUser :one
SELECT EXISTS (
    SELECT 1 FROM transactions
    WHERE user_id = $1
      AND lower(regexp_replace(btrim(category), '\s+', ' ', 'g')) = $2
) AS exists
`

type CategoryTextExistsForUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Category string    `json:"category"`
}

func (q *Queries) CategoryTextExistsForUser(ctx context.Context, arg CategoryTextExistsForUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, categoryTextExistsForUser, arg.UserID, arg.Category)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCategoryMappingsForGroup = `-- name: CountCategoryMappingsForGroup :one
SELECT COUNT(*)::bigint AS count
FROM category_mappings
WHERE group_id = $1 AND user_id = $2
`

type CountCategoryMappingsForGroupParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) CountCategoryMappingsForGroup(ctx context.Context, arg CountCategoryMappingsForGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoryMappingsForGroup, arg.GroupID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCategoryGroup = `-- name: DeleteCategoryGroup :exec
DELETE FROM category_groups
WHERE id = $1 AND user_id = $2
`

type DeleteCategoryGroupParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteCategoryGroup(ctx context.Context, arg DeleteCategoryGroupParams) error {
	_, err := q.db.Exec(ctx, deleteCategoryGroup, arg.ID, arg.UserID)
	return err
}

const deleteCategoryGroupIfEmpty = `-- name: DeleteCategoryGroupIfEmpty :exec
DELETE FROM category_groups cg
WHERE cg.id = $1
  AND cg.user_id = $2
  AND NOT EXISTS (
      SELECT 1 FROM category_mappings cm WHERE cm.group_id = cg.id
  )
`

type DeleteCategoryGroupIfEmptyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteCategoryGroupIfEmpty(ctx context.Context, arg DeleteCategoryGroupIfEmptyParams) error {
	_, err := q.db.Exec(ctx, deleteCategoryGroupIfEmpty, arg.ID, arg.UserID)
	return err
}

const deleteCategoryMapping = `-- name: DeleteCategoryMapping :exec
DELETE FROM category_mappings
WHERE id = $1 AND user_id = $2
`

type DeleteCategoryMappingParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteCategoryMapping(ctx context.Context, arg DeleteCategoryMappingParams) error {
	_, err := q.db.Exec(ctx, deleteCategoryMapping, arg.ID, arg.UserID)
	return err
}

const getCategoryGroup = `-- name: GetCategoryGroup :one
SELECT id, user_id, name, normalized_name, created_at, updated_at FROM category_groups
WHERE id = $1 AND user_id = $2
`

type GetCategoryGroupParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCategoryGroup(ctx context.Context, arg GetCategoryGroupParams) (CategoryGroup, error) {
	row := q.db.QueryRow(ctx, getCategoryGroup, arg.ID, arg.UserID)
	var i CategoryGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.NormalizedName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryMapping = `-- name: GetCategoryMapping :one
SELECT id, user_id, raw_category, normalized_category, group_id, created_at, updated_at FROM category_mappings
WHERE id = $1 AND user_id = $2
`

type GetCategoryMappingParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCategoryMapping(ctx context.Context, arg GetCategoryMappingParams) (CategoryMapping, error) {
	row := q.db.QueryRow(ctx, getCategoryMapping, arg.ID, arg.UserID)
	var i CategoryMapping
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawCategory,
		&i.NormalizedCategory,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCategoryGroup = `-- name: InsertCategoryGroup :one
INSERT INTO category_groups (user_id, name, normalized_name)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, normalized_name, created_at, updated_at
`

type InsertCategoryGroupParams struct {
	UserID         uuid.UUID `json:"user_id"`
	Name           string    `json:"name"`
	NormalizedName string    `json:"normalized_name"`
}

func (q *Queries) InsertCategoryGroup(ctx context.Context, arg InsertCategoryGroupParams) (CategoryGroup, error) {
	row := q.db.QueryRow(ctx, insertCategoryGroup, arg.UserID, arg.Name, arg.NormalizedName)
	var i CategoryGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.NormalizedName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCategoryMapping = `-- name: InsertCategoryMapping :one
INSERT INTO category_mappings (user_id, raw_category, normalized_category, group_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, raw_category, normalized_category, group_id, created_at, updated_at
`

type InsertCategoryMappingParams struct {
	UserID             uuid.UUID `json:"user_id"`
	RawCategory        string    `json:"raw_category"`
	NormalizedCategory string    `json:"normalized_category"`
	GroupID            uuid.UUID `json:"group_id"`
}

func (q *Queries) InsertCategoryMapping(ctx context.Context, arg InsertCategoryMappingParams) (CategoryMapping, error) {
	row := q.db.QueryRow(ctx, insertCategoryMapping,
		arg.UserID,
		arg.RawCategory,
		arg.NormalizedCategory,
		arg.GroupID,
	)
	var i CategoryMapping
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawCategory,
		&i.NormalizedCategory,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoryGroups = `-- name: ListCategoryGroups :many
SELECT id, user_id, name, normalized_name, created_at, updated_at FROM category_groups
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListCategoryGroups(ctx context.Context, userID uuid.UUID) ([]CategoryGroup, error) {
	rows, err := q.db.Query(ctx, listCategoryGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryGroup
	for rows.Next() {
		var i CategoryGroup
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.NormalizedName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryMappings = `-- name: ListCategoryMappings :many
SELECT
    cm.id,
    cm.user_id,
    cm.raw_category,
    cm.normalized_category,
    cm.group_id,
    cm.created_at,
    cm.updated_at,
    cg.name AS group_name
FROM category_mappings cm
JOIN category_groups cg ON cg.id = cm.group_id
WHERE cm.user_id = $1
ORDER BY cg.name, cm.raw_category
`

type ListCategoryMappingsRow struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	RawCategory        string             `json:"raw_category"`
	NormalizedCategory string             `json:"normalized_category"`
	GroupID            uuid.UUID          `json:"group_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	GroupName          string             `json:"group_name"`
}

func (q *Queries) ListCategoryMappings(ctx context.Context, userID uuid.UUID) ([]ListCategoryMappingsRow, error) {
	rows, err := q.db.Query(ctx, listCategoryMappings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryMappingsRow
	for rows.Next() {
		var i ListCategoryMappingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawCategory,
			&i.NormalizedCategory,
			&i.GroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryMappingsByGroup = `-- name: ListCategoryMappingsByGroup :many
SELECT id, user_id, raw_category, normalized_category, group_id, created_at, updated_at FROM category_mappings
WHERE group_id = $1 AND user_id = $2
ORDER BY raw_category
`

type ListCategoryMappingsByGroupParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) ListCategoryMappingsByGroup(ctx context.Context, arg ListCategoryMappingsByGroupParams) ([]CategoryMapping, error) {
	rows, err := q.db.Query(ctx, listCategoryMappingsByGroup, arg.GroupID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryMapping
	for rows.Next() {
		var i CategoryMapping
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawCategory,
			&i.NormalizedCategory,
			&i.GroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnmappedCategoryTexts = `-- name: ListUnmappedCategoryTexts :many
SELECT DISTINCT t.category
FROM transactions t
WHERE t.user_id = $1
  AND btrim(t.category) <> ''
  AND NOT EXISTS (
      SELECT 1 FROM category_mappings cm
      WHERE cm.user_id = t.user_id
        AND cm.normalized_category = lower(regexp_replace(btrim(t.category), '\s+', ' ', 'g'))
  )
ORDER BY t.category
`

func (q *Queries) ListUnmappedCategoryTexts(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUnmappedCategoryTexts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategoryGroupName = `-- name: UpdateCategoryGroupName :one
UPDATE category_groups
SET name = $3,
    normalized_name = $4,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, normalized_name, created_at, updated_at
`

type UpdateCategoryGroupNameParams struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Name           string    `json:"name"`
	NormalizedName string    `json:"normalized_name"`
}

func (q *Queries) UpdateCategoryGroupName(ctx context.Context, arg UpdateCategoryGroupNameParams) (CategoryGroup, error) {
	row := q.db.QueryRow(ctx, updateCategoryGroupName,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.NormalizedName,
	)
	var i CategoryGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.NormalizedName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategoryMappingGroup = `-- name: UpdateCategoryMappingGroup :one
UPDATE category_mappings
SET group_id = $3,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, raw_category, normalized_category, group_id, created_at, updated_at
`

type UpdateCategoryMappingGroupParams struct {
	ID      uuid.UUID `json:"id"`
	UserID  uuid.UUID `json:"user_id"`
	GroupID uuid.UUID `json:"group_id"`
}

func (q *Queries) UpdateCategoryMappingGroup(ctx context.Context, arg UpdateCategoryMappingGroupParams) (CategoryMapping, error) {
	row := q.db.QueryRow(ctx, updateCategoryMappingGroup, arg.ID, arg.UserID, arg.GroupID)
	var i CategoryMapping
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawCategory,
		&i.NormalizedCategory,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
