package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

// InsertChitTransferParentsBatch queues all parent inserts in one database
// round trip while keeping the SQL source and parameter types generated by sqlc.
func InsertChitTransferParentsBatch(ctx context.Context, tx pgx.Tx, args []InsertChitTransferParentParams) ([]uuid.UUID, error) {
	ids := make([]uuid.UUID, 0, len(args))
	if len(args) == 0 {
		return ids, nil
	}
	batch := &pgx.Batch{}
	for _, arg := range args {
		batch.Queue(insertChitTransferParent,
			arg.UserID,
			arg.Name,
			arg.Organizer,
			arg.ChitValue,
			arg.ExpectedMonthly,
			arg.TotalInstallments,
			arg.StartMonth,
		)
	}
	results := tx.SendBatch(ctx, batch)
	for range args {
		var id uuid.UUID
		if err := results.QueryRow().Scan(&id); err != nil {
			_ = results.Close()
			return nil, err
		}
		ids = append(ids, id)
	}
	if err := results.Close(); err != nil {
		return nil, err
	}
	return ids, nil
}

// InsertChitTransferInstallmentsBatch queues all child inserts in one database
// round trip and preserves the ownership check from the generated query.
func InsertChitTransferInstallmentsBatch(ctx context.Context, tx pgx.Tx, args []InsertChitTransferInstallmentParams) error {
	if len(args) == 0 {
		return nil
	}
	batch := &pgx.Batch{}
	for _, arg := range args {
		batch.Queue(insertChitTransferInstallment,
			arg.ChitID,
			arg.Amount,
			arg.PaidOn,
			arg.Note,
			arg.UserID,
		)
	}
	results := tx.SendBatch(ctx, batch)
	for range args {
		var id uuid.UUID
		if err := results.QueryRow().Scan(&id); err != nil {
			_ = results.Close()
			return err
		}
	}
	return results.Close()
}
