// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chits.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countInstallmentsForChit = `-- name: CountInstallmentsForChit :one
SELECT COUNT(*)::bigint AS installment_count
FROM chit_installments
WHERE chit_id = $1
`

func (q *Queries) CountInstallmentsForChit(ctx context.Context, chitID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInstallmentsForChit, chitID)
	var installment_count int64
	err := row.Scan(&installment_count)
	return installment_count, err
}

const deleteChit = `-- name: DeleteChit :execrows
DELETE FROM chits WHERE id = $1 AND user_id = $2
`

type DeleteChitParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteChit(ctx context.Context, arg DeleteChitParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChit, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChitInstallment = `-- name: DeleteChitInstallment :execrows
DELETE FROM chit_installments i
USING chits c
WHERE i.id = $1
  AND i.chit_id = $2
  AND c.id = i.chit_id
  AND c.user_id = $3
`

type DeleteChitInstallmentParams struct {
	ID     uuid.UUID `json:"id"`
	ChitID uuid.UUID `json:"chit_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteChitInstallment(ctx context.Context, arg DeleteChitInstallmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChitInstallment, arg.ID, arg.ChitID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChit = `-- name: GetChit :one
SELECT
    c.id,
    c.user_id,
    c.name,
    c.organizer,
    c.chit_value,
    c.expected_monthly,
    c.total_installments,
    c.start_month,
    c.created_at,
    c.updated_at,
    COUNT(i.id)::bigint AS installment_count,
    COALESCE(SUM(i.amount), 0)::numeric AS total_paid
FROM chits c
LEFT JOIN chit_installments i ON i.chit_id = c.id
WHERE c.id = $1 AND c.user_id = $2
GROUP BY c.id
`

type GetChitParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetChitRow struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	Name              string             `json:"name"`
	Organizer         string             `json:"organizer"`
	ChitValue         pgtype.Numeric     `json:"chit_value"`
	ExpectedMonthly   pgtype.Numeric     `json:"expected_monthly"`
	TotalInstallments int32              `json:"total_installments"`
	StartMonth        pgtype.Date        `json:"start_month"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	InstallmentCount  int64              `json:"installment_count"`
	TotalPaid         pgtype.Numeric     `json:"total_paid"`
}

func (q *Queries) GetChit(ctx context.Context, arg GetChitParams) (GetChitRow, error) {
	row := q.db.QueryRow(ctx, getChit, arg.ID, arg.UserID)
	var i GetChitRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Organizer,
		&i.ChitValue,
		&i.ExpectedMonthly,
		&i.TotalInstallments,
		&i.StartMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstallmentCount,
		&i.TotalPaid,
	)
	return i, err
}

const insertChit = `-- name: InsertChit :one
INSERT INTO chits (
    user_id, name, organizer, chit_value, expected_monthly,
    total_installments, start_month
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
RETURNING id, user_id, name, organizer, chit_value, expected_monthly, total_installments, start_month, created_at, updated_at
`

type InsertChitParams struct {
	UserID            uuid.UUID      `json:"user_id"`
	Name              string         `json:"name"`
	Organizer         string         `json:"organizer"`
	ChitValue         pgtype.Numeric `json:"chit_value"`
	ExpectedMonthly   pgtype.Numeric `json:"expected_monthly"`
	TotalInstallments int32          `json:"total_installments"`
	StartMonth        pgtype.Date    `json:"start_month"`
}

func (q *Queries) InsertChit(ctx context.Context, arg InsertChitParams) (Chit, error) {
	row := q.db.QueryRow(ctx, insertChit,
		arg.UserID,
		arg.Name,
		arg.Organizer,
		arg.ChitValue,
		arg.ExpectedMonthly,
		arg.TotalInstallments,
		arg.StartMonth,
	)
	var i Chit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Organizer,
		&i.ChitValue,
		&i.ExpectedMonthly,
		&i.TotalInstallments,
		&i.StartMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChitInstallment = `-- name: InsertChitInstallment :one
INSERT INTO chit_installments (chit_id, amount, paid_on, note)
SELECT $1, $2, $3, $4
FROM chits c
WHERE c.id = $1 AND c.user_id = $5
RETURNING id, chit_id, amount, paid_on, note, created_at
`

type InsertChitInstallmentParams struct {
	ChitID uuid.UUID      `json:"chit_id"`
	Amount pgtype.Numeric `json:"amount"`
	PaidOn pgtype.Date    `json:"paid_on"`
	Note   string         `json:"note"`
	UserID uuid.UUID      `json:"user_id"`
}

func (q *Queries) InsertChitInstallment(ctx context.Context, arg InsertChitInstallmentParams) (ChitInstallment, error) {
	row := q.db.QueryRow(ctx, insertChitInstallment,
		arg.ChitID,
		arg.Amount,
		arg.PaidOn,
		arg.Note,
		arg.UserID,
	)
	var i ChitInstallment
	err := row.Scan(
		&i.ID,
		&i.ChitID,
		&i.Amount,
		&i.PaidOn,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listChits = `-- name: ListChits :many
SELECT
    c.id,
    c.user_id,
    c.name,
    c.organizer,
    c.chit_value,
    c.expected_monthly,
    c.total_installments,
    c.start_month,
    c.created_at,
    c.updated_at,
    COUNT(i.id)::bigint AS installment_count,
    COALESCE(SUM(i.amount), 0)::numeric AS total_paid
FROM chits c
LEFT JOIN chit_installments i ON i.chit_id = c.id
WHERE c.user_id = $1
GROUP BY c.id
ORDER BY c.created_at DESC
`

type ListChitsRow struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	Name              string             `json:"name"`
	Organizer         string             `json:"organizer"`
	ChitValue         pgtype.Numeric     `json:"chit_value"`
	ExpectedMonthly   pgtype.Numeric     `json:"expected_monthly"`
	TotalInstallments int32              `json:"total_installments"`
	StartMonth        pgtype.Date        `json:"start_month"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	InstallmentCount  int64              `json:"installment_count"`
	TotalPaid         pgtype.Numeric     `json:"total_paid"`
}

func (q *Queries) ListChits(ctx context.Context, userID uuid.UUID) ([]ListChitsRow, error) {
	rows, err := q.db.Query(ctx, listChits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChitsRow
	for rows.Next() {
		var i ListChitsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Organizer,
			&i.ChitValue,
			&i.ExpectedMonthly,
			&i.TotalInstallments,
			&i.StartMonth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstallmentCount,
			&i.TotalPaid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallmentsForChit = `-- name: ListInstallmentsForChit :many
SELECT i.id, i.chit_id, i.amount, i.paid_on, i.note, i.created_at
FROM chit_installments i
JOIN chits c ON c.id = i.chit_id
WHERE i.chit_id = $1 AND c.user_id = $2
ORDER BY i.paid_on ASC, i.created_at ASC, i.id ASC
`

type ListInstallmentsForChitParams struct {
	ChitID uuid.UUID `json:"chit_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ListInstallmentsForChit(ctx context.Context, arg ListInstallmentsForChitParams) ([]ChitInstallment, error) {
	rows, err := q.db.Query(ctx, listInstallmentsForChit, arg.ChitID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChitInstallment
	for rows.Next() {
		var i ChitInstallment
		if err := rows.Scan(
			&i.ID,
			&i.ChitID,
			&i.Amount,
			&i.PaidOn,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChitForUser = `-- name: LockChitForUser :one
SELECT id, user_id, name, organizer, chit_value, expected_monthly,
       total_installments, start_month, created_at, updated_at
FROM chits
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type LockChitForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) LockChitForUser(ctx context.Context, arg LockChitForUserParams) (Chit, error) {
	row := q.db.QueryRow(ctx, lockChitForUser, arg.ID, arg.UserID)
	var i Chit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Organizer,
		&i.ChitValue,
		&i.ExpectedMonthly,
		&i.TotalInstallments,
		&i.StartMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChit = `-- name: UpdateChit :one
UPDATE chits
SET name               = $1,
    organizer          = $2,
    chit_value         = $3,
    expected_monthly   = $4,
    total_installments = $5,
    start_month        = $6,
    updated_at         = now()
WHERE id = $7 AND user_id = $8
RETURNING id, user_id, name, organizer, chit_value, expected_monthly, total_installments, start_month, created_at, updated_at
`

type UpdateChitParams struct {
	Name              string         `json:"name"`
	Organizer         string         `json:"organizer"`
	ChitValue         pgtype.Numeric `json:"chit_value"`
	ExpectedMonthly   pgtype.Numeric `json:"expected_monthly"`
	TotalInstallments int32          `json:"total_installments"`
	StartMonth        pgtype.Date    `json:"start_month"`
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateChit(ctx context.Context, arg UpdateChitParams) (Chit, error) {
	row := q.db.QueryRow(ctx, updateChit,
		arg.Name,
		arg.Organizer,
		arg.ChitValue,
		arg.ExpectedMonthly,
		arg.TotalInstallments,
		arg.StartMonth,
		arg.ID,
		arg.UserID,
	)
	var i Chit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Organizer,
		&i.ChitValue,
		&i.ExpectedMonthly,
		&i.TotalInstallments,
		&i.StartMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChitInstallment = `-- name: UpdateChitInstallment :one
UPDATE chit_installments i
SET amount  = $1,
    paid_on = $2,
    note    = $3
FROM chits c
WHERE i.id = $4
  AND i.chit_id = $5
  AND c.id = i.chit_id
  AND c.user_id = $6
RETURNING i.id, i.chit_id, i.amount, i.paid_on, i.note, i.created_at
`

type UpdateChitInstallmentParams struct {
	Amount pgtype.Numeric `json:"amount"`
	PaidOn pgtype.Date    `json:"paid_on"`
	Note   string         `json:"note"`
	ID     uuid.UUID      `json:"id"`
	ChitID uuid.UUID      `json:"chit_id"`
	UserID uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateChitInstallment(ctx context.Context, arg UpdateChitInstallmentParams) (ChitInstallment, error) {
	row := q.db.QueryRow(ctx, updateChitInstallment,
		arg.Amount,
		arg.PaidOn,
		arg.Note,
		arg.ID,
		arg.ChitID,
		arg.UserID,
	)
	var i ChitInstallment
	err := row.Scan(
		&i.ID,
		&i.ChitID,
		&i.Amount,
		&i.PaidOn,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
