// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events(user_id,name,note,target_date,status,suggestions_enabled)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, user_id, name, note, target_date, status, suggestions_enabled, version, created_at, updated_at, deleted_at, converted_transaction_id
`

type CreateEventParams struct {
	UserID             uuid.UUID   `json:"user_id"`
	Name               string      `json:"name"`
	Note               string      `json:"note"`
	TargetDate         pgtype.Date `json:"target_date"`
	Status             string      `json:"status"`
	SuggestionsEnabled bool        `json:"suggestions_enabled"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.UserID,
		arg.Name,
		arg.Note,
		arg.TargetDate,
		arg.Status,
		arg.SuggestionsEnabled,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Note,
		&i.TargetDate,
		&i.Status,
		&i.SuggestionsEnabled,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ConvertedTransactionID,
	)
	return i, err
}

const deleteMissingEventItems = `-- name: DeleteMissingEventItems :exec
DELETE FROM event_items WHERE event_id=$1 AND NOT (id=ANY($2::uuid[]))
`

type DeleteMissingEventItemsParams struct {
	EventID     uuid.UUID   `json:"event_id"`
	RetainedIds []uuid.UUID `json:"retained_ids"`
}

func (q *Queries) DeleteMissingEventItems(ctx context.Context, arg DeleteMissingEventItemsParams) error {
	_, err := q.db.Exec(ctx, deleteMissingEventItems, arg.EventID, arg.RetainedIds)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, user_id, name, note, target_date, status, suggestions_enabled, version, created_at, updated_at, deleted_at, converted_transaction_id FROM events WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL
`

type GetEventParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, arg.ID, arg.UserID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Note,
		&i.TargetDate,
		&i.Status,
		&i.SuggestionsEnabled,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ConvertedTransactionID,
	)
	return i, err
}

const listEventItems = `-- name: ListEventItems :many
SELECT i.id, i.event_id, i.name, i.expected_cost, i.actual_cost, i.position, i.created_at, i.updated_at FROM event_items i JOIN events e ON e.id=i.event_id
WHERE e.id=$1 AND e.user_id=$2 AND e.deleted_at IS NULL ORDER BY i.position
`

type ListEventItemsParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ListEventItems(ctx context.Context, arg ListEventItemsParams) ([]EventItem, error) {
	rows, err := q.db.Query(ctx, listEventItems, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventItem
	for rows.Next() {
		var i EventItem
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.ExpectedCost,
			&i.ActualCost,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.user_id, e.name, e.note, e.target_date, e.status, e.suggestions_enabled, e.version, e.created_at, e.updated_at, e.deleted_at, e.converted_transaction_id, COUNT(i.id)::bigint AS item_count,
 COALESCE(SUM(i.expected_cost),0)::numeric AS expected_total,
 COALESCE(SUM(i.actual_cost),0)::numeric AS actual_total,
 COUNT(i.id) FILTER (WHERE i.expected_cost IS NULL)::bigint AS missing_expected_count,
 COUNT(i.id) FILTER (WHERE i.actual_cost IS NULL)::bigint AS missing_actual_count
FROM events e LEFT JOIN event_items i ON i.event_id=e.id
WHERE e.user_id=$1 AND e.deleted_at IS NULL
 AND ($2::text='' OR e.status=$2)
 AND (NOT $3::boolean OR (e.status='planned' AND e.suggestions_enabled AND (e.target_date IS NULL OR e.target_date < $4::date)))
GROUP BY e.id
HAVING NOT $3::boolean OR
 (COUNT(i.id)>0 AND COUNT(i.id) FILTER (WHERE i.expected_cost IS NULL)=0 AND SUM(i.expected_cost)<=$5::numeric)
ORDER BY CASE WHEN $3::boolean THEN e.target_date END ASC NULLS LAST,
 e.created_at DESC,e.id
LIMIT $7 OFFSET $6
`

type ListEventsParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	StatusFilter string         `json:"status_filter"`
	Suggestions  bool           `json:"suggestions"`
	BeforeDate   pgtype.Date    `json:"before_date"`
	Allowance    pgtype.Numeric `json:"allowance"`
	PageOffset   int32          `json:"page_offset"`
	PageLimit    int32          `json:"page_limit"`
}

type ListEventsRow struct {
	ID                     uuid.UUID          `json:"id"`
	UserID                 uuid.UUID          `json:"user_id"`
	Name                   string             `json:"name"`
	Note                   string             `json:"note"`
	TargetDate             pgtype.Date        `json:"target_date"`
	Status                 string             `json:"status"`
	SuggestionsEnabled     bool               `json:"suggestions_enabled"`
	Version                int64              `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	ConvertedTransactionID pgtype.UUID        `json:"converted_transaction_id"`
	ItemCount              int64              `json:"item_count"`
	ExpectedTotal          pgtype.Numeric     `json:"expected_total"`
	ActualTotal            pgtype.Numeric     `json:"actual_total"`
	MissingExpectedCount   int64              `json:"missing_expected_count"`
	MissingActualCount     int64              `json:"missing_actual_count"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.UserID,
		arg.StatusFilter,
		arg.Suggestions,
		arg.BeforeDate,
		arg.Allowance,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Note,
			&i.TargetDate,
			&i.Status,
			&i.SuggestionsEnabled,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ConvertedTransactionID,
			&i.ItemCount,
			&i.ExpectedTotal,
			&i.ActualTotal,
			&i.MissingExpectedCount,
			&i.MissingActualCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEvent = `-- name: LockEvent :one
SELECT id, user_id, name, note, target_date, status, suggestions_enabled, version, created_at, updated_at, deleted_at, converted_transaction_id FROM events WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL FOR UPDATE
`

type LockEventParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) LockEvent(ctx context.Context, arg LockEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, lockEvent, arg.ID, arg.UserID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Note,
		&i.TargetDate,
		&i.Status,
		&i.SuggestionsEnabled,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ConvertedTransactionID,
	)
	return i, err
}

const markEventConverted = `-- name: MarkEventConverted :one
UPDATE events
SET converted_transaction_id=$3,target_date=$4,version=version+1,updated_at=now()
WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL
RETURNING id, user_id, name, note, target_date, status, suggestions_enabled, version, created_at, updated_at, deleted_at, converted_transaction_id
`

type MarkEventConvertedParams struct {
	ID                     uuid.UUID   `json:"id"`
	UserID                 uuid.UUID   `json:"user_id"`
	ConvertedTransactionID pgtype.UUID `json:"converted_transaction_id"`
	TargetDate             pgtype.Date `json:"target_date"`
}

func (q *Queries) MarkEventConverted(ctx context.Context, arg MarkEventConvertedParams) (Event, error) {
	row := q.db.QueryRow(ctx, markEventConverted,
		arg.ID,
		arg.UserID,
		arg.ConvertedTransactionID,
		arg.TargetDate,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Note,
		&i.TargetDate,
		&i.Status,
		&i.SuggestionsEnabled,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ConvertedTransactionID,
	)
	return i, err
}

const saveEventItem = `-- name: SaveEventItem :exec
INSERT INTO event_items(id,event_id,name,expected_cost,actual_cost,position)
VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,expected_cost=EXCLUDED.expected_cost,
actual_cost=EXCLUDED.actual_cost,position=EXCLUDED.position,updated_at=now()
WHERE event_items.event_id=EXCLUDED.event_id
`

type SaveEventItemParams struct {
	ID           uuid.UUID      `json:"id"`
	EventID      uuid.UUID      `json:"event_id"`
	Name         string         `json:"name"`
	ExpectedCost pgtype.Numeric `json:"expected_cost"`
	ActualCost   pgtype.Numeric `json:"actual_cost"`
	Position     int32          `json:"position"`
}

func (q *Queries) SaveEventItem(ctx context.Context, arg SaveEventItemParams) error {
	_, err := q.db.Exec(ctx, saveEventItem,
		arg.ID,
		arg.EventID,
		arg.Name,
		arg.ExpectedCost,
		arg.ActualCost,
		arg.Position,
	)
	return err
}

const softDeleteEvent = `-- name: SoftDeleteEvent :exec
UPDATE events SET deleted_at=now(),updated_at=now(),version=version+1 WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL
`

type SoftDeleteEventParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteEvent(ctx context.Context, arg SoftDeleteEventParams) error {
	_, err := q.db.Exec(ctx, softDeleteEvent, arg.ID, arg.UserID)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET name=$3,note=$4,target_date=$5,status=$6,suggestions_enabled=$7,version=version+1,updated_at=now()
WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL RETURNING id, user_id, name, note, target_date, status, suggestions_enabled, version, created_at, updated_at, deleted_at, converted_transaction_id
`

type UpdateEventParams struct {
	ID                 uuid.UUID   `json:"id"`
	UserID             uuid.UUID   `json:"user_id"`
	Name               string      `json:"name"`
	Note               string      `json:"note"`
	TargetDate         pgtype.Date `json:"target_date"`
	Status             string      `json:"status"`
	SuggestionsEnabled bool        `json:"suggestions_enabled"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Note,
		arg.TargetDate,
		arg.Status,
		arg.SuggestionsEnabled,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Note,
		&i.TargetDate,
		&i.Status,
		&i.SuggestionsEnabled,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ConvertedTransactionID,
	)
	return i, err
}
