// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lents.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLent = `-- name: DeleteLent :execrows
DELETE FROM lents WHERE id = $1 AND user_id = $2
`

type DeleteLentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteLent(ctx context.Context, arg DeleteLentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLent, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRepayment = `-- name: DeleteRepayment :execrows
DELETE FROM lent_repayments r
USING lents l
WHERE r.id = $1
  AND r.lent_id = $2
  AND l.id = r.lent_id
  AND l.user_id = $3
`

type DeleteRepaymentParams struct {
	ID     uuid.UUID `json:"id"`
	LentID uuid.UUID `json:"lent_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteRepayment(ctx context.Context, arg DeleteRepaymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRepayment, arg.ID, arg.LentID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLent = `-- name: GetLent :one
SELECT l.id, l.user_id, l.counterparty, l.amount, l.lent_on, l.due_on, l.note,
       COALESCE(r.total, 0)::numeric            AS repaid_total,
       (l.amount - COALESCE(r.total, 0))::numeric AS outstanding
FROM lents l
LEFT JOIN (
    SELECT lent_id, SUM(amount) AS total FROM lent_repayments GROUP BY lent_id
) r ON r.lent_id = l.id
WHERE l.id = $1 AND l.user_id = $2
`

type GetLentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetLentRow struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	Counterparty string         `json:"counterparty"`
	Amount       pgtype.Numeric `json:"amount"`
	LentOn       pgtype.Date    `json:"lent_on"`
	DueOn        pgtype.Date    `json:"due_on"`
	Note         string         `json:"note"`
	RepaidTotal  pgtype.Numeric `json:"repaid_total"`
	Outstanding  pgtype.Numeric `json:"outstanding"`
}

func (q *Queries) GetLent(ctx context.Context, arg GetLentParams) (GetLentRow, error) {
	row := q.db.QueryRow(ctx, getLent, arg.ID, arg.UserID)
	var i GetLentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Counterparty,
		&i.Amount,
		&i.LentOn,
		&i.DueOn,
		&i.Note,
		&i.RepaidTotal,
		&i.Outstanding,
	)
	return i, err
}

const insertLent = `-- name: InsertLent :one
INSERT INTO lents (user_id, counterparty, amount, lent_on, due_on, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, counterparty, amount, lent_on, due_on, note, created_at, updated_at
`

type InsertLentParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	Counterparty string         `json:"counterparty"`
	Amount       pgtype.Numeric `json:"amount"`
	LentOn       pgtype.Date    `json:"lent_on"`
	DueOn        pgtype.Date    `json:"due_on"`
	Note         string         `json:"note"`
}

func (q *Queries) InsertLent(ctx context.Context, arg InsertLentParams) (Lent, error) {
	row := q.db.QueryRow(ctx, insertLent,
		arg.UserID,
		arg.Counterparty,
		arg.Amount,
		arg.LentOn,
		arg.DueOn,
		arg.Note,
	)
	var i Lent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Counterparty,
		&i.Amount,
		&i.LentOn,
		&i.DueOn,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRepayment = `-- name: InsertRepayment :one
INSERT INTO lent_repayments (lent_id, amount, repaid_on, note)
SELECT $1, $2, $3, $4
FROM lents l
WHERE l.id = $1 AND l.user_id = $5
RETURNING id, lent_id, amount, repaid_on, note, created_at
`

type InsertRepaymentParams struct {
	LentID   uuid.UUID      `json:"lent_id"`
	Amount   pgtype.Numeric `json:"amount"`
	RepaidOn pgtype.Date    `json:"repaid_on"`
	Note     string         `json:"note"`
	UserID   uuid.UUID      `json:"user_id"`
}

func (q *Queries) InsertRepayment(ctx context.Context, arg InsertRepaymentParams) (LentRepayment, error) {
	row := q.db.QueryRow(ctx, insertRepayment,
		arg.LentID,
		arg.Amount,
		arg.RepaidOn,
		arg.Note,
		arg.UserID,
	)
	var i LentRepayment
	err := row.Scan(
		&i.ID,
		&i.LentID,
		&i.Amount,
		&i.RepaidOn,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listLents = `-- name: ListLents :many
SELECT l.id, l.user_id, l.counterparty, l.amount, l.lent_on, l.due_on, l.note,
       COALESCE(r.total, 0)::numeric            AS repaid_total,
       (l.amount - COALESCE(r.total, 0))::numeric AS outstanding
FROM lents l
LEFT JOIN (
    SELECT lent_id, SUM(amount) AS total FROM lent_repayments GROUP BY lent_id
) r ON r.lent_id = l.id
WHERE l.user_id = $1
  AND (
    $2::text = 'all'
    OR ($2::text = 'open'    AND l.amount - COALESCE(r.total, 0) > 0)
    OR ($2::text = 'settled' AND l.amount - COALESCE(r.total, 0) <= 0)
  )
ORDER BY l.lent_on DESC, l.created_at DESC
`

type ListLentsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

type ListLentsRow struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	Counterparty string         `json:"counterparty"`
	Amount       pgtype.Numeric `json:"amount"`
	LentOn       pgtype.Date    `json:"lent_on"`
	DueOn        pgtype.Date    `json:"due_on"`
	Note         string         `json:"note"`
	RepaidTotal  pgtype.Numeric `json:"repaid_total"`
	Outstanding  pgtype.Numeric `json:"outstanding"`
}

func (q *Queries) ListLents(ctx context.Context, arg ListLentsParams) ([]ListLentsRow, error) {
	rows, err := q.db.Query(ctx, listLents, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLentsRow
	for rows.Next() {
		var i ListLentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Counterparty,
			&i.Amount,
			&i.LentOn,
			&i.DueOn,
			&i.Note,
			&i.RepaidTotal,
			&i.Outstanding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepaymentsForLent = `-- name: ListRepaymentsForLent :many
SELECT r.id, r.lent_id, r.amount, r.repaid_on, r.note
FROM lent_repayments r
JOIN lents l ON l.id = r.lent_id
WHERE r.lent_id = $1 AND l.user_id = $2
ORDER BY r.repaid_on ASC, r.created_at ASC
`

type ListRepaymentsForLentParams struct {
	LentID uuid.UUID `json:"lent_id"`
	UserID uuid.UUID `json:"user_id"`
}

type ListRepaymentsForLentRow struct {
	ID       uuid.UUID      `json:"id"`
	LentID   uuid.UUID      `json:"lent_id"`
	Amount   pgtype.Numeric `json:"amount"`
	RepaidOn pgtype.Date    `json:"repaid_on"`
	Note     string         `json:"note"`
}

func (q *Queries) ListRepaymentsForLent(ctx context.Context, arg ListRepaymentsForLentParams) ([]ListRepaymentsForLentRow, error) {
	rows, err := q.db.Query(ctx, listRepaymentsForLent, arg.LentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepaymentsForLentRow
	for rows.Next() {
		var i ListRepaymentsForLentRow
		if err := rows.Scan(
			&i.ID,
			&i.LentID,
			&i.Amount,
			&i.RepaidOn,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumLentOutstanding = `-- name: SumLentOutstanding :one
SELECT
    COUNT(*)::bigint                                        AS open_count,
    COALESCE(SUM(l.amount - COALESCE(r.total, 0)), 0)::numeric AS outstanding_total
FROM lents l
LEFT JOIN (
    SELECT lent_id, SUM(amount) AS total FROM lent_repayments GROUP BY lent_id
) r ON r.lent_id = l.id
WHERE l.user_id = $1
  AND l.amount - COALESCE(r.total, 0) > 0
`

type SumLentOutstandingRow struct {
	OpenCount        int64          `json:"open_count"`
	OutstandingTotal pgtype.Numeric `json:"outstanding_total"`
}

func (q *Queries) SumLentOutstanding(ctx context.Context, userID uuid.UUID) (SumLentOutstandingRow, error) {
	row := q.db.QueryRow(ctx, sumLentOutstanding, userID)
	var i SumLentOutstandingRow
	err := row.Scan(&i.OpenCount, &i.OutstandingTotal)
	return i, err
}

const sumRepaymentsForLent = `-- name: SumRepaymentsForLent :one
SELECT COALESCE(SUM(r.amount), 0)::numeric AS repaid_total
FROM lent_repayments r
WHERE r.lent_id = $1
  AND r.id <> $2
`

type SumRepaymentsForLentParams struct {
	LentID    uuid.UUID `json:"lent_id"`
	ExcludeID uuid.UUID `json:"exclude_id"`
}

// Total already repaid against a lent, optionally excluding one repayment row
// (used when editing an existing repayment so it does not count against itself).
func (q *Queries) SumRepaymentsForLent(ctx context.Context, arg SumRepaymentsForLentParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumRepaymentsForLent, arg.LentID, arg.ExcludeID)
	var repaid_total pgtype.Numeric
	err := row.Scan(&repaid_total)
	return repaid_total, err
}

const updateLent = `-- name: UpdateLent :one
UPDATE lents
SET counterparty = $1,
    amount       = $2,
    lent_on      = $3,
    due_on       = $4,
    note         = $5,
    updated_at   = now()
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, counterparty, amount, lent_on, due_on, note, created_at, updated_at
`

type UpdateLentParams struct {
	Counterparty string         `json:"counterparty"`
	Amount       pgtype.Numeric `json:"amount"`
	LentOn       pgtype.Date    `json:"lent_on"`
	DueOn        pgtype.Date    `json:"due_on"`
	Note         string         `json:"note"`
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateLent(ctx context.Context, arg UpdateLentParams) (Lent, error) {
	row := q.db.QueryRow(ctx, updateLent,
		arg.Counterparty,
		arg.Amount,
		arg.LentOn,
		arg.DueOn,
		arg.Note,
		arg.ID,
		arg.UserID,
	)
	var i Lent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Counterparty,
		&i.Amount,
		&i.LentOn,
		&i.DueOn,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepayment = `-- name: UpdateRepayment :one
UPDATE lent_repayments r
SET amount    = $1,
    repaid_on = $2,
    note      = $3
FROM lents l
WHERE r.id = $4
  AND r.lent_id = $5
  AND l.id = r.lent_id
  AND l.user_id = $6
RETURNING r.id, r.lent_id, r.amount, r.repaid_on, r.note, r.created_at
`

type UpdateRepaymentParams struct {
	Amount   pgtype.Numeric `json:"amount"`
	RepaidOn pgtype.Date    `json:"repaid_on"`
	Note     string         `json:"note"`
	ID       uuid.UUID      `json:"id"`
	LentID   uuid.UUID      `json:"lent_id"`
	UserID   uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateRepayment(ctx context.Context, arg UpdateRepaymentParams) (LentRepayment, error) {
	row := q.db.QueryRow(ctx, updateRepayment,
		arg.Amount,
		arg.RepaidOn,
		arg.Note,
		arg.ID,
		arg.LentID,
		arg.UserID,
	)
	var i LentRepayment
	err := row.Scan(
		&i.ID,
		&i.LentID,
		&i.Amount,
		&i.RepaidOn,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
