// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Section string

const (
	SectionEssential Section = "essential"
	SectionFlexible  Section = "flexible"
	SectionDaily     Section = "daily"
	SectionIncome    Section = "income"
)

func (e *Section) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Section(s)
	case string:
		*e = Section(s)
	default:
		return fmt.Errorf("unsupported scan type for Section: %T", src)
	}
	return nil
}

type NullSection struct {
	Section Section `json:"section"`
	Valid   bool    `json:"valid"` // Valid is true if Section is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSection) Scan(value interface{}) error {
	if value == nil {
		ns.Section, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Section.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Section), nil
}

type TxnKind string

const (
	TxnKindCash       TxnKind = "cash"
	TxnKindCredit     TxnKind = "credit"
	TxnKindSettlement TxnKind = "settlement"
)

func (e *TxnKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TxnKind(s)
	case string:
		*e = TxnKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TxnKind: %T", src)
	}
	return nil
}

type NullTxnKind struct {
	TxnKind TxnKind `json:"txn_kind"`
	Valid   bool    `json:"valid"` // Valid is true if TxnKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTxnKind) Scan(value interface{}) error {
	if value == nil {
		ns.TxnKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TxnKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTxnKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TxnKind), nil
}

type CategoryGroup struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CategoryMapping struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	RawCategory        string             `json:"raw_category"`
	NormalizedCategory string             `json:"normalized_category"`
	GroupID            uuid.UUID          `json:"group_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Lent struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Counterparty string             `json:"counterparty"`
	Amount       pgtype.Numeric     `json:"amount"`
	LentOn       pgtype.Date        `json:"lent_on"`
	DueOn        pgtype.Date        `json:"due_on"`
	Note         string             `json:"note"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type LentRepayment struct {
	ID        uuid.UUID          `json:"id"`
	LentID    uuid.UUID          `json:"lent_id"`
	Amount    pgtype.Numeric     `json:"amount"`
	RepaidOn  pgtype.Date        `json:"repaid_on"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MonthState struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
	Closed bool      `json:"closed"`
	Seeded bool      `json:"seeded"`
}

type SettlementLink struct {
	SettlementID uuid.UUID `json:"settlement_id"`
	CreditID     uuid.UUID `json:"credit_id"`
}

type Template struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	Section  Section   `json:"section"`
	Label    string    `json:"label"`
	Position int32     `json:"position"`
}

type Transaction struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Section   Section            `json:"section"`
	Category  string             `json:"category"`
	Amount    pgtype.Numeric     `json:"amount"`
	TxnDate   pgtype.Date        `json:"txn_date"`
	Kind      TxnKind            `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TransactionNameSuggestion struct {
	UserID         uuid.UUID          `json:"user_id"`
	Section        Section            `json:"section"`
	NormalizedName string             `json:"normalized_name"`
	DisplayName    string             `json:"display_name"`
	UseCount       int64              `json:"use_count"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserSetting struct {
	UserID          uuid.UUID          `json:"user_id"`
	BudgetEssential pgtype.Numeric     `json:"budget_essential"`
	BudgetFlexible  pgtype.Numeric     `json:"budget_flexible"`
	BudgetDaily     pgtype.Numeric     `json:"budget_daily"`
	Currency        string             `json:"currency"`
	Theme           string             `json:"theme"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
