// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monthly_budgets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMonthlyBudget = `-- name: GetMonthlyBudget :one
SELECT user_id, month, budget_essential, budget_flexible, budget_daily, created_at, updated_at FROM monthly_budgets
WHERE user_id = $1
  AND month = $2
`

type GetMonthlyBudgetParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Month  pgtype.Date `json:"month"`
}

func (q *Queries) GetMonthlyBudget(ctx context.Context, arg GetMonthlyBudgetParams) (MonthlyBudget, error) {
	row := q.db.QueryRow(ctx, getMonthlyBudget, arg.UserID, arg.Month)
	var i MonthlyBudget
	err := row.Scan(
		&i.UserID,
		&i.Month,
		&i.BudgetEssential,
		&i.BudgetFlexible,
		&i.BudgetDaily,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMonthlyBudgets = `-- name: ListMonthlyBudgets :many
SELECT user_id, month, budget_essential, budget_flexible, budget_daily, created_at, updated_at FROM monthly_budgets
WHERE user_id = $1
ORDER BY month DESC
`

func (q *Queries) ListMonthlyBudgets(ctx context.Context, userID uuid.UUID) ([]MonthlyBudget, error) {
	rows, err := q.db.Query(ctx, listMonthlyBudgets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyBudget
	for rows.Next() {
		var i MonthlyBudget
		if err := rows.Scan(
			&i.UserID,
			&i.Month,
			&i.BudgetEssential,
			&i.BudgetFlexible,
			&i.BudgetDaily,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMonthlyBudget = `-- name: UpsertMonthlyBudget :one
INSERT INTO monthly_budgets (
    user_id,
    month,
    budget_essential,
    budget_flexible,
    budget_daily
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (user_id, month) DO UPDATE
SET budget_essential = EXCLUDED.budget_essential,
    budget_flexible  = EXCLUDED.budget_flexible,
    budget_daily     = EXCLUDED.budget_daily,
    updated_at       = now()
RETURNING user_id, month, budget_essential, budget_flexible, budget_daily, created_at, updated_at
`

type UpsertMonthlyBudgetParams struct {
	UserID          uuid.UUID      `json:"user_id"`
	Month           pgtype.Date    `json:"month"`
	BudgetEssential pgtype.Numeric `json:"budget_essential"`
	BudgetFlexible  pgtype.Numeric `json:"budget_flexible"`
	BudgetDaily     pgtype.Numeric `json:"budget_daily"`
}

func (q *Queries) UpsertMonthlyBudget(ctx context.Context, arg UpsertMonthlyBudgetParams) (MonthlyBudget, error) {
	row := q.db.QueryRow(ctx, upsertMonthlyBudget,
		arg.UserID,
		arg.Month,
		arg.BudgetEssential,
		arg.BudgetFlexible,
		arg.BudgetDaily,
	)
	var i MonthlyBudget
	err := row.Scan(
		&i.UserID,
		&i.Month,
		&i.BudgetEssential,
		&i.BudgetFlexible,
		&i.BudgetDaily,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
