// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: month_state.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getMonthState = `-- name: GetMonthState :one
SELECT user_id, month, closed, seeded FROM month_state WHERE user_id = $1 AND month = $2
`

type GetMonthStateParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
}

func (q *Queries) GetMonthState(ctx context.Context, arg GetMonthStateParams) (MonthState, error) {
	row := q.db.QueryRow(ctx, getMonthState, arg.UserID, arg.Month)
	var i MonthState
	err := row.Scan(
		&i.UserID,
		&i.Month,
		&i.Closed,
		&i.Seeded,
	)
	return i, err
}

const listMonthStates = `-- name: ListMonthStates :many
SELECT user_id, month, closed, seeded FROM month_state WHERE user_id = $1 ORDER BY month
`

func (q *Queries) ListMonthStates(ctx context.Context, userID uuid.UUID) ([]MonthState, error) {
	rows, err := q.db.Query(ctx, listMonthStates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthState
	for rows.Next() {
		var i MonthState
		if err := rows.Scan(
			&i.UserID,
			&i.Month,
			&i.Closed,
			&i.Seeded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMonthSeeded = `-- name: MarkMonthSeeded :one
INSERT INTO month_state (user_id, month, seeded)
VALUES ($1, $2, true)
ON CONFLICT (user_id, month) DO UPDATE
    SET seeded = true
RETURNING user_id, month, closed, seeded
`

type MarkMonthSeededParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
}

func (q *Queries) MarkMonthSeeded(ctx context.Context, arg MarkMonthSeededParams) (MonthState, error) {
	row := q.db.QueryRow(ctx, markMonthSeeded, arg.UserID, arg.Month)
	var i MonthState
	err := row.Scan(
		&i.UserID,
		&i.Month,
		&i.Closed,
		&i.Seeded,
	)
	return i, err
}

const upsertMonthClosed = `-- name: UpsertMonthClosed :one
INSERT INTO month_state (user_id, month, closed)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, month) DO UPDATE
    SET closed = EXCLUDED.closed
RETURNING user_id, month, closed, seeded
`

type UpsertMonthClosedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
	Closed bool      `json:"closed"`
}

func (q *Queries) UpsertMonthClosed(ctx context.Context, arg UpsertMonthClosedParams) (MonthState, error) {
	row := q.db.QueryRow(ctx, upsertMonthClosed, arg.UserID, arg.Month, arg.Closed)
	var i MonthState
	err := row.Scan(
		&i.UserID,
		&i.Month,
		&i.Closed,
		&i.Seeded,
	)
	return i, err
}
