// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reserves.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveReserves = `-- name: CountActiveReserves :one
SELECT COUNT(*)::bigint FROM reserves
WHERE user_id = $1 AND archived_at IS NULL
`

func (q *Queries) CountActiveReserves(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveReserves, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createReserve = `-- name: CreateReserve :one
INSERT INTO reserves (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, is_general, archived_at, created_at, updated_at
`

type CreateReserveParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateReserve(ctx context.Context, arg CreateReserveParams) (Reserve, error) {
	row := q.db.QueryRow(ctx, createReserve, arg.UserID, arg.Name)
	var i Reserve
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsGeneral,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureGeneralReserve = `-- name: EnsureGeneralReserve :exec
INSERT INTO reserves (user_id, name, is_general)
VALUES ($1, 'General Reserve', true)
ON CONFLICT (user_id) WHERE is_general DO NOTHING
`

func (q *Queries) EnsureGeneralReserve(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureGeneralReserve, userID)
	return err
}

const getReserveForUser = `-- name: GetReserveForUser :one
SELECT r.id, r.user_id, r.name, r.is_general, r.archived_at, r.created_at, r.updated_at,
       reserve_balance(r.id) AS balance
FROM reserves r
WHERE r.id = $1 AND r.user_id = $2
`

type GetReserveForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetReserveForUserRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	IsGeneral  bool               `json:"is_general"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Balance    pgtype.Numeric     `json:"balance"`
}

func (q *Queries) GetReserveForUser(ctx context.Context, arg GetReserveForUserParams) (GetReserveForUserRow, error) {
	row := q.db.QueryRow(ctx, getReserveForUser, arg.ID, arg.UserID)
	var i GetReserveForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsGeneral,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Balance,
	)
	return i, err
}

const getReserveForUserForUpdate = `-- name: GetReserveForUserForUpdate :one
SELECT id, user_id, name, is_general, archived_at, created_at, updated_at FROM reserves
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type GetReserveForUserForUpdateParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetReserveForUserForUpdate(ctx context.Context, arg GetReserveForUserForUpdateParams) (Reserve, error) {
	row := q.db.QueryRow(ctx, getReserveForUserForUpdate, arg.ID, arg.UserID)
	var i Reserve
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsGeneral,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReserves = `-- name: ListReserves :many
SELECT r.id, r.user_id, r.name, r.is_general, r.archived_at, r.created_at, r.updated_at,
       reserve_balance(r.id) AS balance
FROM reserves r
WHERE r.user_id = $1
  AND ($2::boolean OR r.archived_at IS NULL)
ORDER BY (r.archived_at IS NOT NULL), r.is_general DESC, r.created_at, r.id
`

type ListReservesParams struct {
	UserID          uuid.UUID `json:"user_id"`
	IncludeArchived bool      `json:"include_archived"`
}

type ListReservesRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	IsGeneral  bool               `json:"is_general"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Balance    pgtype.Numeric     `json:"balance"`
}

func (q *Queries) ListReserves(ctx context.Context, arg ListReservesParams) ([]ListReservesRow, error) {
	rows, err := q.db.Query(ctx, listReserves, arg.UserID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservesRow
	for rows.Next() {
		var i ListReservesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.IsGeneral,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserForReserveCount = `-- name: LockUserForReserveCount :one
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUserForReserveCount(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockUserForReserveCount, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const renameReserve = `-- name: RenameReserve :one
UPDATE reserves
SET name = $1, updated_at = now()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, name, is_general, archived_at, created_at, updated_at
`

type RenameReserveParams struct {
	Name   string    `json:"name"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RenameReserve(ctx context.Context, arg RenameReserveParams) (Reserve, error) {
	row := q.db.QueryRow(ctx, renameReserve, arg.Name, arg.ID, arg.UserID)
	var i Reserve
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsGeneral,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveBalance = `-- name: ReserveBalance :one
SELECT reserve_balance($1)
`

func (q *Queries) ReserveBalance(ctx context.Context, reserveID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, reserveBalance, reserveID)
	var reserve_balance pgtype.Numeric
	err := row.Scan(&reserve_balance)
	return reserve_balance, err
}

const reserveNameExists = `-- name: ReserveNameExists :one
SELECT EXISTS (
  SELECT 1 FROM reserves r
  WHERE r.user_id = $1 AND lower(r.name) = lower($2) AND r.id <> $3
)
`

type ReserveNameExistsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	ExcludeID uuid.UUID `json:"exclude_id"`
}

func (q *Queries) ReserveNameExists(ctx context.Context, arg ReserveNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, reserveNameExists, arg.UserID, arg.Name, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
