// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reserves.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveReserves = `-- name: CountActiveReserves :one
SELECT COUNT(*)::bigint FROM reserves
WHERE user_id = $1 AND archived_at IS NULL
`

func (q *Queries) CountActiveReserves(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveReserves, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createReserve = `-- name: CreateReserve :one
INSERT INTO reserves (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, is_general, archived_at, created_at, updated_at
`

type CreateReserveParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateReserve(ctx context.Context, arg CreateReserveParams) (Reserve, error) {
	row := q.db.QueryRow(ctx, createReserve, arg.UserID, arg.Name)
	var i Reserve
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsGeneral,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureGeneralReserve = `-- name: EnsureGeneralReserve :exec
INSERT INTO reserves (user_id, name, is_general)
VALUES ($1, 'General Reserve', true)
ON CONFLICT (user_id) WHERE is_general DO NOTHING
`

func (q *Queries) EnsureGeneralReserve(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureGeneralReserve, userID)
	return err
}

const getReserveForUser = `-- name: GetReserveForUser :one
SELECT r.id, r.user_id, r.name, r.is_general, r.archived_at, r.created_at, r.updated_at,
       reserve_balance(r.id) AS balance
FROM reserves r
WHERE r.id = $1 AND r.user_id = $2
`

type GetReserveForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetReserveForUserRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	IsGeneral  bool               `json:"is_general"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Balance    pgtype.Numeric     `json:"balance"`
}

func (q *Queries) GetReserveForUser(ctx context.Context, arg GetReserveForUserParams) (GetReserveForUserRow, error) {
	row := q.db.QueryRow(ctx, getReserveForUser, arg.ID, arg.UserID)
	var i GetReserveForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsGeneral,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Balance,
	)
	return i, err
}

const getReserveForUserForUpdate = `-- name: GetReserveForUserForUpdate :one
SELECT id, user_id, name, is_general, archived_at, created_at, updated_at FROM reserves
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type GetReserveForUserForUpdateParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetReserveForUserForUpdate(ctx context.Context, arg GetReserveForUserForUpdateParams) (Reserve, error) {
	row := q.db.QueryRow(ctx, getReserveForUserForUpdate, arg.ID, arg.UserID)
	var i Reserve
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsGeneral,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReserveEntry = `-- name: InsertReserveEntry :one
INSERT INTO reserve_entries (operation_id, reserve_id, direction, amount)
VALUES ($1, $2, $3, $4)
RETURNING id, operation_id, reserve_id, direction, amount, created_at
`

type InsertReserveEntryParams struct {
	OperationID uuid.UUID      `json:"operation_id"`
	ReserveID   uuid.UUID      `json:"reserve_id"`
	Direction   string         `json:"direction"`
	Amount      pgtype.Numeric `json:"amount"`
}

func (q *Queries) InsertReserveEntry(ctx context.Context, arg InsertReserveEntryParams) (ReserveEntry, error) {
	row := q.db.QueryRow(ctx, insertReserveEntry,
		arg.OperationID,
		arg.ReserveID,
		arg.Direction,
		arg.Amount,
	)
	var i ReserveEntry
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.ReserveID,
		&i.Direction,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const insertReserveOperation = `-- name: InsertReserveOperation :one
INSERT INTO reserve_operations (user_id, operation_type, occurred_on, description, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, operation_type, occurred_on, description, note, created_at, updated_at
`

type InsertReserveOperationParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	OperationType string      `json:"operation_type"`
	OccurredOn    pgtype.Date `json:"occurred_on"`
	Description   string      `json:"description"`
	Note          string      `json:"note"`
}

func (q *Queries) InsertReserveOperation(ctx context.Context, arg InsertReserveOperationParams) (ReserveOperation, error) {
	row := q.db.QueryRow(ctx, insertReserveOperation,
		arg.UserID,
		arg.OperationType,
		arg.OccurredOn,
		arg.Description,
		arg.Note,
	)
	var i ReserveOperation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OperationType,
		&i.OccurredOn,
		&i.Description,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepositOperationHistory = `-- name: ListDepositOperationHistory :many
SELECT o.id, o.operation_type, o.occurred_on, o.description, o.note, o.created_at, o.updated_at,
       e.id AS entry_id, e.reserve_id, r.name AS reserve_name, e.direction, e.amount
FROM reserve_operations o
JOIN reserve_entries e ON e.operation_id = o.id
JOIN reserves r ON r.id = e.reserve_id
WHERE o.user_id = $1
  AND o.operation_type = 'deposit'
  AND o.occurred_on >= $2
  AND o.occurred_on < $3
  AND (
    $4::text = ''
    OR EXISTS (
      SELECT 1 FROM reserve_entries filtered
      WHERE filtered.operation_id = o.id
        AND filtered.reserve_id = $4::uuid
    )
  )
ORDER BY o.occurred_on DESC, o.created_at DESC, o.id DESC, r.name, e.id
`

type ListDepositOperationHistoryParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	FromDate  pgtype.Date `json:"from_date"`
	ToDate    pgtype.Date `json:"to_date"`
	ReserveID string      `json:"reserve_id"`
}

type ListDepositOperationHistoryRow struct {
	ID            uuid.UUID          `json:"id"`
	OperationType string             `json:"operation_type"`
	OccurredOn    pgtype.Date        `json:"occurred_on"`
	Description   string             `json:"description"`
	Note          string             `json:"note"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	EntryID       uuid.UUID          `json:"entry_id"`
	ReserveID     uuid.UUID          `json:"reserve_id"`
	ReserveName   string             `json:"reserve_name"`
	Direction     string             `json:"direction"`
	Amount        pgtype.Numeric     `json:"amount"`
}

func (q *Queries) ListDepositOperationHistory(ctx context.Context, arg ListDepositOperationHistoryParams) ([]ListDepositOperationHistoryRow, error) {
	rows, err := q.db.Query(ctx, listDepositOperationHistory,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.ReserveID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDepositOperationHistoryRow
	for rows.Next() {
		var i ListDepositOperationHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.OperationType,
			&i.OccurredOn,
			&i.Description,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryID,
			&i.ReserveID,
			&i.ReserveName,
			&i.Direction,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReserves = `-- name: ListReserves :many
SELECT r.id, r.user_id, r.name, r.is_general, r.archived_at, r.created_at, r.updated_at,
       reserve_balance(r.id) AS balance
FROM reserves r
WHERE r.user_id = $1
  AND ($2::boolean OR r.archived_at IS NULL)
ORDER BY (r.archived_at IS NOT NULL), r.is_general DESC, r.created_at, r.id
`

type ListReservesParams struct {
	UserID          uuid.UUID `json:"user_id"`
	IncludeArchived bool      `json:"include_archived"`
}

type ListReservesRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	IsGeneral  bool               `json:"is_general"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Balance    pgtype.Numeric     `json:"balance"`
}

func (q *Queries) ListReserves(ctx context.Context, arg ListReservesParams) ([]ListReservesRow, error) {
	rows, err := q.db.Query(ctx, listReserves, arg.UserID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservesRow
	for rows.Next() {
		var i ListReservesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.IsGeneral,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReservesForDeposit = `-- name: LockReservesForDeposit :many
SELECT id, user_id, name, is_general, archived_at, created_at, updated_at FROM reserves
WHERE user_id = $1
  AND id = ANY($2::uuid[])
ORDER BY id
FOR UPDATE
`

type LockReservesForDepositParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	ReserveIds []uuid.UUID `json:"reserve_ids"`
}

func (q *Queries) LockReservesForDeposit(ctx context.Context, arg LockReservesForDepositParams) ([]Reserve, error) {
	rows, err := q.db.Query(ctx, lockReservesForDeposit, arg.UserID, arg.ReserveIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reserve
	for rows.Next() {
		var i Reserve
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.IsGeneral,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserForReserveCount = `-- name: LockUserForReserveCount :one
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUserForReserveCount(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockUserForReserveCount, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const renameReserve = `-- name: RenameReserve :one
UPDATE reserves
SET name = $1, updated_at = now()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, name, is_general, archived_at, created_at, updated_at
`

type RenameReserveParams struct {
	Name   string    `json:"name"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RenameReserve(ctx context.Context, arg RenameReserveParams) (Reserve, error) {
	row := q.db.QueryRow(ctx, renameReserve, arg.Name, arg.ID, arg.UserID)
	var i Reserve
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsGeneral,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveBalance = `-- name: ReserveBalance :one
SELECT reserve_balance($1)
`

func (q *Queries) ReserveBalance(ctx context.Context, reserveID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, reserveBalance, reserveID)
	var reserve_balance pgtype.Numeric
	err := row.Scan(&reserve_balance)
	return reserve_balance, err
}

const reserveNameExists = `-- name: ReserveNameExists :one
SELECT EXISTS (
  SELECT 1 FROM reserves r
  WHERE r.user_id = $1 AND lower(r.name) = lower($2) AND r.id <> $3
)
`

type ReserveNameExistsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	ExcludeID uuid.UUID `json:"exclude_id"`
}

func (q *Queries) ReserveNameExists(ctx context.Context, arg ReserveNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, reserveNameExists, arg.UserID, arg.Name, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
