// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteTemplatesBySection = `-- name: DeleteTemplatesBySection :exec
DELETE FROM templates
WHERE user_id = $1 AND section = $2
`

type DeleteTemplatesBySectionParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Section Section   `json:"section"`
}

func (q *Queries) DeleteTemplatesBySection(ctx context.Context, arg DeleteTemplatesBySectionParams) error {
	_, err := q.db.Exec(ctx, deleteTemplatesBySection, arg.UserID, arg.Section)
	return err
}

const insertTemplate = `-- name: InsertTemplate :one
INSERT INTO templates (user_id, section, label, position)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, section, label, position
`

type InsertTemplateParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Section  Section   `json:"section"`
	Label    string    `json:"label"`
	Position int32     `json:"position"`
}

func (q *Queries) InsertTemplate(ctx context.Context, arg InsertTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, insertTemplate,
		arg.UserID,
		arg.Section,
		arg.Label,
		arg.Position,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Section,
		&i.Label,
		&i.Position,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, user_id, section, label, position FROM templates
WHERE user_id = $1
ORDER BY section, position
`

func (q *Queries) ListTemplates(ctx context.Context, userID uuid.UUID) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Section,
			&i.Label,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesBySection = `-- name: ListTemplatesBySection :many
SELECT id, user_id, section, label, position FROM templates
WHERE user_id = $1 AND section = $2
ORDER BY position
`

type ListTemplatesBySectionParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Section Section   `json:"section"`
}

func (q *Queries) ListTemplatesBySection(ctx context.Context, arg ListTemplatesBySectionParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesBySection, arg.UserID, arg.Section)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Section,
			&i.Label,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
