// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction_search.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const searchTransactions = `-- name: SearchTransactions :many
WITH input AS (
    SELECT normalize_transaction_search($2::text) AS value
), patterns AS (
    -- ! is the LIKE escape character; user wildcards remain literal.
    SELECT value, replace(replace(replace(value, '!', '!!'), '%', '!%'), '_', '!_') AS literal
    FROM input
), ranked AS (
    SELECT t.id, t.txn_date,
        CASE WHEN t.normalized_name = p.value THEN 0
             WHEN t.normalized_name LIKE p.literal || '%' ESCAPE '!' THEN 1
             WHEN t.normalized_name LIKE '%' || p.literal || '%' ESCAPE '!' THEN 2
             ELSE 3 END::integer AS match_tier,
        round((similarity(t.normalized_name, p.value) * 1000000)::numeric)::integer AS score
    FROM transactions t CROSS JOIN patterns p
    WHERE t.user_id = $3
      AND ($4::text IS NULL OR t.section::text = $4::text)
      AND ($5::text IS NULL OR t.kind::text = $5::text)
      AND ($6::date IS NULL OR t.txn_date >= $6::date)
      AND ($7::date IS NULL OR t.txn_date <= $7::date)
      AND ($8::numeric IS NULL OR t.amount >= $8::numeric)
      AND ($9::numeric IS NULL OR t.amount <= $9::numeric)
      AND (
          (char_length(p.value) < 3 AND t.normalized_name LIKE p.literal || '%' ESCAPE '!')
          OR (char_length(p.value) >= 3 AND (
              t.normalized_name LIKE '%' || p.literal || '%' ESCAPE '!'
              OR t.normalized_name % p.value
          ))
      )
), page AS MATERIALIZED (
    SELECT id, txn_date, match_tier, score FROM ranked
    WHERE NOT $10::boolean
        OR ($1::text = 'relevance' AND (
            match_tier > $11::integer
            OR (match_tier = $11::integer AND score < $12::integer)
            OR (match_tier = $11::integer AND score = $12::integer
                AND (txn_date, id) < ($13::date, $14::uuid))
        ))
        OR ($1::text = 'date_desc'
            AND (txn_date, id) < ($13::date, $14::uuid))
        OR ($1::text = 'date_asc'
            AND (txn_date, id) > ($13::date, $14::uuid))
    ORDER BY
        CASE WHEN $1::text = 'relevance' THEN match_tier END,
        CASE WHEN $1::text = 'relevance' THEN score END DESC,
        CASE WHEN $1::text = 'date_asc' THEN txn_date END ASC,
        CASE WHEN $1::text = 'date_asc' THEN id END ASC,
        txn_date DESC, id DESC
    LIMIT $15
)
SELECT t.id, t.user_id, t.section, t.category, t.amount, t.txn_date, t.kind, t.created_at, t.updated_at, t.normalized_name, page.match_tier, page.score,
    EXISTS (
        SELECT 1 FROM settlement_links sl
        JOIN transactions s ON s.id = sl.settlement_id
        WHERE sl.credit_id = t.id AND s.user_id = t.user_id
    ) AS settled,
    ARRAY (
        SELECT sl.credit_id FROM settlement_links sl
        JOIN transactions c ON c.id = sl.credit_id
        WHERE sl.settlement_id = t.id AND c.user_id = t.user_id
        ORDER BY sl.credit_id
    )::uuid[] AS settles
FROM page JOIN transactions t ON t.id = page.id
ORDER BY
    CASE WHEN $1::text = 'relevance' THEN page.match_tier END,
    CASE WHEN $1::text = 'relevance' THEN page.score END DESC,
    CASE WHEN $1::text = 'date_asc' THEN page.txn_date END ASC,
    CASE WHEN $1::text = 'date_asc' THEN page.id END ASC,
    page.txn_date DESC, page.id DESC
`

type SearchTransactionsParams struct {
	SortMode    string         `json:"sort_mode"`
	Search      string         `json:"search"`
	UserID      uuid.UUID      `json:"user_id"`
	Section     *string        `json:"section"`
	Kind        *string        `json:"kind"`
	FromDate    pgtype.Date    `json:"from_date"`
	ToDate      pgtype.Date    `json:"to_date"`
	MinAmount   pgtype.Numeric `json:"min_amount"`
	MaxAmount   pgtype.Numeric `json:"max_amount"`
	HasCursor   bool           `json:"has_cursor"`
	CursorTier  int32          `json:"cursor_tier"`
	CursorScore int32          `json:"cursor_score"`
	CursorDate  pgtype.Date    `json:"cursor_date"`
	CursorID    uuid.UUID      `json:"cursor_id"`
	ResultLimit int32          `json:"result_limit"`
}

type SearchTransactionsRow struct {
	Transaction Transaction `json:"transaction"`
	MatchTier   int32       `json:"match_tier"`
	Score       int32       `json:"score"`
	Settled     bool        `json:"settled"`
	Settles     []uuid.UUID `json:"settles"`
}

func (q *Queries) SearchTransactions(ctx context.Context, arg SearchTransactionsParams) ([]SearchTransactionsRow, error) {
	rows, err := q.db.Query(ctx, searchTransactions,
		arg.SortMode,
		arg.Search,
		arg.UserID,
		arg.Section,
		arg.Kind,
		arg.FromDate,
		arg.ToDate,
		arg.MinAmount,
		arg.MaxAmount,
		arg.HasCursor,
		arg.CursorTier,
		arg.CursorScore,
		arg.CursorDate,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTransactionsRow
	for rows.Next() {
		var i SearchTransactionsRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.UserID,
			&i.Transaction.Section,
			&i.Transaction.Category,
			&i.Transaction.Amount,
			&i.Transaction.TxnDate,
			&i.Transaction.Kind,
			&i.Transaction.CreatedAt,
			&i.Transaction.UpdatedAt,
			&i.Transaction.NormalizedName,
			&i.MatchTier,
			&i.Score,
			&i.Settled,
			&i.Settles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
