// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const dailyCategorySuggestions = `-- name: DailyCategorySuggestions :many
SELECT DISTINCT category FROM transactions
WHERE user_id = $1 AND section = 'daily' AND kind <> 'settlement' AND category <> ''
ORDER BY category
`

// Distinct non-settlement daily categories for ghost autocomplete.
func (q *Queries) DailyCategorySuggestions(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, dailyCategorySuggestions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSettlementLinks = `-- name: DeleteSettlementLinks :exec
DELETE FROM settlement_links WHERE settlement_id = $1
`

func (q *Queries) DeleteSettlementLinks(ctx context.Context, settlementID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSettlementLinks, settlementID)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, section, category, amount, txn_date, kind, created_at, updated_at FROM transactions
WHERE id = $1 AND user_id = $2
`

type GetTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Section,
		&i.Category,
		&i.Amount,
		&i.TxnDate,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incomeCategorySuggestions = `-- name: IncomeCategorySuggestions :many
SELECT DISTINCT category FROM transactions
WHERE user_id = $1 AND section = 'income' AND category <> ''
ORDER BY category
`

// Distinct income source categories for ghost autocomplete.
func (q *Queries) IncomeCategorySuggestions(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, incomeCategorySuggestions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSettlementLink = `-- name: InsertSettlementLink :exec
INSERT INTO settlement_links (settlement_id, credit_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertSettlementLinkParams struct {
	SettlementID uuid.UUID `json:"settlement_id"`
	CreditID     uuid.UUID `json:"credit_id"`
}

func (q *Queries) InsertSettlementLink(ctx context.Context, arg InsertSettlementLinkParams) error {
	_, err := q.db.Exec(ctx, insertSettlementLink, arg.SettlementID, arg.CreditID)
	return err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (user_id, section, category, amount, txn_date, kind)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, section, category, amount, txn_date, kind, created_at, updated_at
`

type InsertTransactionParams struct {
	UserID   uuid.UUID      `json:"user_id"`
	Section  Section        `json:"section"`
	Category string         `json:"category"`
	Amount   pgtype.Numeric `json:"amount"`
	TxnDate  pgtype.Date    `json:"txn_date"`
	Kind     TxnKind        `json:"kind"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.UserID,
		arg.Section,
		arg.Category,
		arg.Amount,
		arg.TxnDate,
		arg.Kind,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Section,
		&i.Category,
		&i.Amount,
		&i.TxnDate,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCreditTransactionsByDateRange = `-- name: ListCreditTransactionsByDateRange :many
SELECT id, user_id, section, category, amount, txn_date, kind, created_at, updated_at FROM transactions
WHERE user_id = $1
  AND txn_date >= $2
  AND txn_date <  $3
  AND section IN ('essential','flexible','daily')
  AND kind = 'credit'
ORDER BY txn_date, created_at
`

type ListCreditTransactionsByDateRangeParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

// Expense credit rows in a half-open [from, to) date window, for the credit
// drill-down. Mirrors SumCreditUsage's filter so totals reconcile.
func (q *Queries) ListCreditTransactionsByDateRange(ctx context.Context, arg ListCreditTransactionsByDateRangeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listCreditTransactionsByDateRange, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Section,
			&i.Category,
			&i.Amount,
			&i.TxnDate,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksForSettlement = `-- name: ListLinksForSettlement :many
SELECT credit_id FROM settlement_links WHERE settlement_id = $1
`

func (q *Queries) ListLinksForSettlement(ctx context.Context, settlementID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLinksForSettlement, settlementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var credit_id uuid.UUID
		if err := rows.Scan(&credit_id); err != nil {
			return nil, err
		}
		items = append(items, credit_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementLinksByMonth = `-- name: ListSettlementLinksByMonth :many

SELECT sl.settlement_id, sl.credit_id
FROM settlement_links sl
JOIN transactions s ON s.id = sl.settlement_id
WHERE s.user_id = $1 AND to_char(s.txn_date, 'YYYY-MM') = $2::text
`

type ListSettlementLinksByMonthParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
}

// ---- settlement links --------------------------------------------------
// All (settlement_id, credit_id) pairs where the SETTLEMENT falls in the month.
func (q *Queries) ListSettlementLinksByMonth(ctx context.Context, arg ListSettlementLinksByMonthParams) ([]SettlementLink, error) {
	rows, err := q.db.Query(ctx, listSettlementLinksByMonth, arg.UserID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettlementLink
	for rows.Next() {
		var i SettlementLink
		if err := rows.Scan(&i.SettlementID, &i.CreditID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementLinksByYear = `-- name: ListSettlementLinksByYear :many
SELECT sl.settlement_id, sl.credit_id
FROM settlement_links sl
JOIN transactions s ON s.id = sl.settlement_id
WHERE s.user_id = $1 AND to_char(s.txn_date, 'YYYY') = $2::text
`

type ListSettlementLinksByYearParams struct {
	UserID uuid.UUID `json:"user_id"`
	Year   string    `json:"year"`
}

func (q *Queries) ListSettlementLinksByYear(ctx context.Context, arg ListSettlementLinksByYearParams) ([]SettlementLink, error) {
	rows, err := q.db.Query(ctx, listSettlementLinksByYear, arg.UserID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettlementLink
	for rows.Next() {
		var i SettlementLink
		if err := rows.Scan(&i.SettlementID, &i.CreditID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByDateRange = `-- name: ListTransactionsByDateRange :many
SELECT id, user_id, section, category, amount, txn_date, kind, created_at, updated_at FROM transactions
WHERE user_id = $1
  AND txn_date >= $2
  AND txn_date <= $3
  AND kind <> 'settlement'
ORDER BY txn_date, created_at
`

type ListTransactionsByDateRangeParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListTransactionsByDateRange(ctx context.Context, arg ListTransactionsByDateRangeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByDateRange, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Section,
			&i.Category,
			&i.Amount,
			&i.TxnDate,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByMonth = `-- name: ListTransactionsByMonth :many
SELECT id, user_id, section, category, amount, txn_date, kind, created_at, updated_at FROM transactions
WHERE user_id = $1 AND to_char(txn_date, 'YYYY-MM') = $2::text
ORDER BY txn_date, created_at
`

type ListTransactionsByMonthParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
}

func (q *Queries) ListTransactionsByMonth(ctx context.Context, arg ListTransactionsByMonthParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByMonth, arg.UserID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Section,
			&i.Category,
			&i.Amount,
			&i.TxnDate,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByMonthSection = `-- name: ListTransactionsByMonthSection :many
SELECT id, user_id, section, category, amount, txn_date, kind, created_at, updated_at FROM transactions
WHERE user_id = $1
  AND to_char(txn_date, 'YYYY-MM') = $3::text
  AND section = $2
ORDER BY txn_date, created_at
`

type ListTransactionsByMonthSectionParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Section Section   `json:"section"`
	Month   string    `json:"month"`
}

func (q *Queries) ListTransactionsByMonthSection(ctx context.Context, arg ListTransactionsByMonthSectionParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByMonthSection, arg.UserID, arg.Section, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Section,
			&i.Category,
			&i.Amount,
			&i.TxnDate,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByYear = `-- name: ListTransactionsByYear :many
SELECT id, user_id, section, category, amount, txn_date, kind, created_at, updated_at FROM transactions
WHERE user_id = $1 AND to_char(txn_date, 'YYYY') = $2::text
ORDER BY txn_date, created_at
`

type ListTransactionsByYearParams struct {
	UserID uuid.UUID `json:"user_id"`
	Year   string    `json:"year"`
}

func (q *Queries) ListTransactionsByYear(ctx context.Context, arg ListTransactionsByYearParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByYear, arg.UserID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Section,
			&i.Category,
			&i.Amount,
			&i.TxnDate,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openCreditsForSection = `-- name: OpenCreditsForSection :many
SELECT t.id, t.user_id, t.section, t.category, t.amount, t.txn_date, t.kind, t.created_at, t.updated_at FROM transactions t
WHERE t.user_id = $1
  AND t.section = $2
  AND t.kind = 'credit'
  AND NOT EXISTS (
      SELECT 1 FROM settlement_links sl
      WHERE sl.credit_id = t.id
        AND sl.settlement_id <> $3
  )
ORDER BY t.txn_date DESC, t.created_at DESC
`

type OpenCreditsForSectionParams struct {
	UserID            uuid.UUID `json:"user_id"`
	Section           Section   `json:"section"`
	ExcludeSettlement uuid.UUID `json:"exclude_settlement"`
}

// Open (unsettled) credits in a section, newest first — candidates for a settlement
// picker. Excludes any credit already linked to a settlement other than the one
// currently being edited (exclude_settlement).
func (q *Queries) OpenCreditsForSection(ctx context.Context, arg OpenCreditsForSectionParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, openCreditsForSection, arg.UserID, arg.Section, arg.ExcludeSettlement)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Section,
			&i.Category,
			&i.Amount,
			&i.TxnDate,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settledCreditIdsByMonth = `-- name: SettledCreditIdsByMonth :many
SELECT DISTINCT sl.credit_id
FROM settlement_links sl
JOIN transactions c ON c.id = sl.credit_id
WHERE c.user_id = $1 AND to_char(c.txn_date, 'YYYY-MM') = $2::text
`

type SettledCreditIdsByMonthParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  string    `json:"month"`
}

// Credit ids (in this month) that some settlement references — for "Settled" chips.
func (q *Queries) SettledCreditIdsByMonth(ctx context.Context, arg SettledCreditIdsByMonthParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, settledCreditIdsByMonth, arg.UserID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var credit_id uuid.UUID
		if err := rows.Scan(&credit_id); err != nil {
			return nil, err
		}
		items = append(items, credit_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumCreditUsage = `-- name: SumCreditUsage :one
SELECT
  COALESCE(SUM(amount), 0)::numeric AS total,
  COUNT(*)::bigint AS count
FROM transactions
WHERE user_id = $1
  AND txn_date >= $2
  AND txn_date <  $3
  AND section IN ('essential','flexible','daily')
  AND kind = 'credit'
`

type SumCreditUsageParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type SumCreditUsageRow struct {
	Total pgtype.Numeric `json:"total"`
	Count int64          `json:"count"`
}

// Total + count of expense credit transactions in a half-open [from, to) date
// window. Settlement state is irrelevant: settled and unsettled credits both
// count as incurred credit spend.
func (q *Queries) SumCreditUsage(ctx context.Context, arg SumCreditUsageParams) (SumCreditUsageRow, error) {
	row := q.db.QueryRow(ctx, sumCreditUsage, arg.UserID, arg.FromDate, arg.ToDate)
	var i SumCreditUsageRow
	err := row.Scan(&i.Total, &i.Count)
	return i, err
}

const sumDashboardMonthly = `-- name: SumDashboardMonthly :one
SELECT
  COALESCE(SUM(amount) FILTER (WHERE section = 'income'), 0)::numeric AS income,
  COALESCE(SUM(amount) FILTER (
    WHERE section IN ('essential','flexible','daily')
      AND kind IN ('cash','settlement')
  ), 0)::numeric AS cash_flow,
  COALESCE(SUM(amount) FILTER (
    WHERE section IN ('essential','flexible','daily')
      AND kind IN ('cash','credit')
  ), 0)::numeric AS monthly_cost,
  COUNT(*) FILTER (
    WHERE section IN ('essential','flexible','daily')
      AND kind = 'credit'
      AND NOT EXISTS (
        SELECT 1 FROM settlement_links sl WHERE sl.credit_id = transactions.id
      )
  )::bigint AS outstanding_credits_count,
  COALESCE(SUM(amount) FILTER (
    WHERE section IN ('essential','flexible','daily')
      AND kind = 'credit'
      AND NOT EXISTS (
        SELECT 1 FROM settlement_links sl WHERE sl.credit_id = transactions.id
      )
  ), 0)::numeric AS outstanding_credits_total
FROM transactions
WHERE user_id = $1
  AND txn_date >= $2
  AND txn_date <  $3
`

type SumDashboardMonthlyParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type SumDashboardMonthlyRow struct {
	Income                  pgtype.Numeric `json:"income"`
	CashFlow                pgtype.Numeric `json:"cash_flow"`
	MonthlyCost             pgtype.Numeric `json:"monthly_cost"`
	OutstandingCreditsCount int64          `json:"outstanding_credits_count"`
	OutstandingCreditsTotal pgtype.Numeric `json:"outstanding_credits_total"`
}

func (q *Queries) SumDashboardMonthly(ctx context.Context, arg SumDashboardMonthlyParams) (SumDashboardMonthlyRow, error) {
	row := q.db.QueryRow(ctx, sumDashboardMonthly, arg.UserID, arg.FromDate, arg.ToDate)
	var i SumDashboardMonthlyRow
	err := row.Scan(
		&i.Income,
		&i.CashFlow,
		&i.MonthlyCost,
		&i.OutstandingCreditsCount,
		&i.OutstandingCreditsTotal,
	)
	return i, err
}

const sumEssentialSpendByMonths = `-- name: SumEssentialSpendByMonths :many
SELECT to_char(txn_date, 'YYYY-MM') AS month,
       COALESCE(SUM(amount), 0)::numeric AS total
FROM transactions
WHERE user_id = $1
  AND section = 'essential'
  AND kind <> 'settlement'
  AND to_char(txn_date, 'YYYY-MM') = ANY($2::text[])
GROUP BY 1
`

type SumEssentialSpendByMonthsParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 []string  `json:"column_2"`
}

type SumEssentialSpendByMonthsRow struct {
	Month string         `json:"month"`
	Total pgtype.Numeric `json:"total"`
}

func (q *Queries) SumEssentialSpendByMonths(ctx context.Context, arg SumEssentialSpendByMonthsParams) ([]SumEssentialSpendByMonthsRow, error) {
	rows, err := q.db.Query(ctx, sumEssentialSpendByMonths, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumEssentialSpendByMonthsRow
	for rows.Next() {
		var i SumEssentialSpendByMonthsRow
		if err := rows.Scan(&i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET section    = $3,
    category   = $4,
    amount     = $5,
    txn_date   = $6,
    kind       = $7,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, section, category, amount, txn_date, kind, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID       uuid.UUID      `json:"id"`
	UserID   uuid.UUID      `json:"user_id"`
	Section  Section        `json:"section"`
	Category string         `json:"category"`
	Amount   pgtype.Numeric `json:"amount"`
	TxnDate  pgtype.Date    `json:"txn_date"`
	Kind     TxnKind        `json:"kind"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.Section,
		arg.Category,
		arg.Amount,
		arg.TxnDate,
		arg.Kind,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Section,
		&i.Category,
		&i.Amount,
		&i.TxnDate,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
