// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction_name_suggestions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listPopularTransactionNameSuggestions = `-- name: ListPopularTransactionNameSuggestions :many
SELECT display_name
FROM transaction_name_suggestions
WHERE user_id = $1
  AND section = $2
ORDER BY use_count DESC, last_used_at DESC, display_name ASC
LIMIT $3
`

type ListPopularTransactionNameSuggestionsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Section     Section   `json:"section"`
	ResultLimit int32     `json:"result_limit"`
}

func (q *Queries) ListPopularTransactionNameSuggestions(ctx context.Context, arg ListPopularTransactionNameSuggestionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPopularTransactionNameSuggestions, arg.UserID, arg.Section, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var display_name string
		if err := rows.Scan(&display_name); err != nil {
			return nil, err
		}
		items = append(items, display_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchShortTransactionNameSuggestions = `-- name: SearchShortTransactionNameSuggestions :many
WITH normalized_input AS (
    SELECT lower(
        regexp_replace(btrim($4::text), '[[:space:]]+', ' ', 'g')
    ) AS value
)
SELECT tns.display_name
FROM transaction_name_suggestions tns
CROSS JOIN normalized_input ni
WHERE tns.user_id = $1
  AND tns.section = $2
  AND tns.normalized_name LIKE ni.value || '%'
ORDER BY
    (tns.normalized_name = ni.value) DESC,
    tns.use_count DESC,
    tns.last_used_at DESC,
    tns.display_name ASC
LIMIT $3
`

type SearchShortTransactionNameSuggestionsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Section     Section   `json:"section"`
	ResultLimit int32     `json:"result_limit"`
	Search      string    `json:"search"`
}

func (q *Queries) SearchShortTransactionNameSuggestions(ctx context.Context, arg SearchShortTransactionNameSuggestionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, searchShortTransactionNameSuggestions,
		arg.UserID,
		arg.Section,
		arg.ResultLimit,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var display_name string
		if err := rows.Scan(&display_name); err != nil {
			return nil, err
		}
		items = append(items, display_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTransactionNameSuggestions = `-- name: SearchTransactionNameSuggestions :many
WITH normalized_input AS (
    SELECT lower(
        regexp_replace(btrim($4::text), '[[:space:]]+', ' ', 'g')
    ) AS value
)
SELECT tns.display_name
FROM transaction_name_suggestions tns
CROSS JOIN normalized_input ni
WHERE tns.user_id = $1
  AND tns.section = $2
  AND (
      tns.normalized_name LIKE '%' || ni.value || '%'
      OR tns.normalized_name % ni.value
  )
ORDER BY
    (tns.normalized_name = ni.value) DESC,
    (tns.normalized_name LIKE ni.value || '%') DESC,
    (tns.normalized_name LIKE '%' || ni.value || '%') DESC,
    similarity(tns.normalized_name, ni.value) DESC,
    tns.use_count DESC,
    tns.last_used_at DESC,
    tns.display_name ASC
LIMIT $3
`

type SearchTransactionNameSuggestionsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Section     Section   `json:"section"`
	ResultLimit int32     `json:"result_limit"`
	Search      string    `json:"search"`
}

func (q *Queries) SearchTransactionNameSuggestions(ctx context.Context, arg SearchTransactionNameSuggestionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, searchTransactionNameSuggestions,
		arg.UserID,
		arg.Section,
		arg.ResultLimit,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var display_name string
		if err := rows.Scan(&display_name); err != nil {
			return nil, err
		}
		items = append(items, display_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
