// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ensureSettings = `-- name: EnsureSettings :one
INSERT INTO user_settings (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
RETURNING user_id, budget_essential, budget_flexible, budget_daily, currency, theme, updated_at, credit_statement_day
`

// Create the default settings row for a user if it does not exist yet.
func (q *Queries) EnsureSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, ensureSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.BudgetEssential,
		&i.BudgetFlexible,
		&i.BudgetDaily,
		&i.Currency,
		&i.Theme,
		&i.UpdatedAt,
		&i.CreditStatementDay,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT user_id, budget_essential, budget_flexible, budget_daily, currency, theme, updated_at, credit_statement_day FROM user_settings WHERE user_id = $1
`

func (q *Queries) GetSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.BudgetEssential,
		&i.BudgetFlexible,
		&i.BudgetDaily,
		&i.Currency,
		&i.Theme,
		&i.UpdatedAt,
		&i.CreditStatementDay,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, display_name, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBudgets = `-- name: UpdateBudgets :one
UPDATE user_settings
SET budget_essential = $2,
    budget_flexible  = $3,
    budget_daily     = $4,
    updated_at       = now()
WHERE user_id = $1
RETURNING user_id, budget_essential, budget_flexible, budget_daily, currency, theme, updated_at, credit_statement_day
`

type UpdateBudgetsParams struct {
	UserID          uuid.UUID      `json:"user_id"`
	BudgetEssential pgtype.Numeric `json:"budget_essential"`
	BudgetFlexible  pgtype.Numeric `json:"budget_flexible"`
	BudgetDaily     pgtype.Numeric `json:"budget_daily"`
}

func (q *Queries) UpdateBudgets(ctx context.Context, arg UpdateBudgetsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, updateBudgets,
		arg.UserID,
		arg.BudgetEssential,
		arg.BudgetFlexible,
		arg.BudgetDaily,
	)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.BudgetEssential,
		&i.BudgetFlexible,
		&i.BudgetDaily,
		&i.Currency,
		&i.Theme,
		&i.UpdatedAt,
		&i.CreditStatementDay,
	)
	return i, err
}

const updateCreditStatementDay = `-- name: UpdateCreditStatementDay :one
UPDATE user_settings
SET credit_statement_day = $1,
    updated_at           = now()
WHERE user_id = $2
RETURNING user_id, budget_essential, budget_flexible, budget_daily, currency, theme, updated_at, credit_statement_day
`

type UpdateCreditStatementDayParams struct {
	CreditStatementDay *int16    `json:"credit_statement_day"`
	UserID             uuid.UUID `json:"user_id"`
}

// Set or clear (NULL) the credit card statement closing day. Dedicated so a
// currency/theme update never touches this field and vice versa.
func (q *Queries) UpdateCreditStatementDay(ctx context.Context, arg UpdateCreditStatementDayParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, updateCreditStatementDay, arg.CreditStatementDay, arg.UserID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.BudgetEssential,
		&i.BudgetFlexible,
		&i.BudgetDaily,
		&i.Currency,
		&i.Theme,
		&i.UpdatedAt,
		&i.CreditStatementDay,
	)
	return i, err
}

const updatePreferences = `-- name: UpdatePreferences :one
UPDATE user_settings
SET currency   = $2,
    theme      = $3,
    updated_at = now()
WHERE user_id = $1
RETURNING user_id, budget_essential, budget_flexible, budget_daily, currency, theme, updated_at, credit_statement_day
`

type UpdatePreferencesParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Currency string    `json:"currency"`
	Theme    string    `json:"theme"`
}

func (q *Queries) UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, updatePreferences, arg.UserID, arg.Currency, arg.Theme)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.BudgetEssential,
		&i.BudgetFlexible,
		&i.BudgetDaily,
		&i.Currency,
		&i.Theme,
		&i.UpdatedAt,
		&i.CreditStatementDay,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $2,
    email        = $3,
    updated_at   = now()
WHERE id = $1
RETURNING id, email, display_name, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	Email       string    `json:"email"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, email)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
    SET email = EXCLUDED.email,
        updated_at = now()
RETURNING id, email, display_name, created_at, updated_at
`

type UpsertUserParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

// Mirror a Goauth subject into our users table on first sight (and keep email fresh).
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
